version: ~> 1.0
language:
  - cpp
  - c
branches:
  only:
    - master
dist:
  - bionic
jobs:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
    - os: linux
      arch: amd64
      compiler: clang
    - os: linux
      arch: arm64
      compiler: gcc
    - os: linux
      arch: arm64
      compiler: clang
    - os: osx
      osx_image: xcode14.2
      compiler: clang
script:
  - make all
  - build/bin/cxxexample
  - build/bin/cexample
