version: ~> 1.0
language:
  - cpp
  - c
branches:
  only:
    - master
dist:
  - jammy
env: MAKE=make
jobs:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
    - os: linux
      arch: amd64
      compiler: clang
    - os: linux
      arch: arm64
      compiler: gcc
    - os: linux
      arch: arm64
      compiler: clang
    - os: linux
      dist: xenial
      arch: arm64
      compiler: gcc
    - os: freebsd
      addons:
        pkg:
          - gmake
      arch: arm64
      compiler: clang
      env:
        - MAKE=gmake
    - os: osx
      osx_image: xcode14.2
      compiler: clang
    - os: linux-ppc64le
      compiler: gcc
before_script:
  if [ $TRAVIS_OS_NAME = freebsd ]; then sudo ln -s /usr/local/bin/bash /bin/bash; fi
script:
  - $MAKE all
  - build/bin/cxxexample
  - build/bin/cexample
