version: ~> 1.0
language:
  - cpp
  - c
branches:
  only:
    - master
dist:
  - jammy
env: MAKE=make  
jobs:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
    - os: linux
      arch: amd64
      compiler: clang
    - os: linux
      arch: arm64
      compiler: gcc
    - os: linux
      arch: arm64
      compiler: clang
    - os: freebsd
      arch: amd64
      compiler: gcc
      env: MAKE=gmake
    - os: freebsd
      arch: amd64
      compiler: clang
      env: MAKE=gmake      
    - os: osx
      osx_image: xcode14.2
      compiler: clang
script:
  - $MAKE all
  - build/bin/cxxexample
  - build/bin/cexample
install: skip
