---
version: ~> 1.0
language: cpp, c
branches:
    only:
        - master
script:
    - make all
    - build/bin/mkverobj
    - build/bin/cexample
    - build/bin/cxxexample
compiler:
    - clang
    - gcc
    - clang++
    - g++
