---
version: ~> 1.0
language:
  - cpp
  - c
branches:
  only:
    - version-2
os:
  - linux
  - osx
dist:
  - bionic
osx_image:
  - xcode14.3
arch:
  - aarch64
  - armhf
  - arm64
  - amd64
script:
  - make all
compiler:
  - clang
  - gcc
  - clang++
  - g++
